version: '3'
services:
  todo-service:
    build: ./todo-service
    ports:
      - "3000:3000"
    environment:
      - DB_URL=mongodb+srv://velikara:JrieOfUlA3M0T7x8@cluster0.b26cd0w.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - DB_USER=velikara
      - DB_PASSWORD=JrieOfUlA3M0T7x8
  todo-ui:
    build: ./todo-ui
    ports:
      - "80:80"